### ISSUE TITLE
ZIP Dataset training failed

### ISSUE THREAD

**Issue by GrantPerkins** [wpilibsuite/Axon#184]
Tried training with [Oxford Pet Dataset](https://public.roboflow.com/object-detection/oxford-pets)

```
datasets copied
[90m[2m[1][22m[39m 17189591-1ed3-4d63-a828-ccae26e21022: Trainer extracting dataset
[90m[2m[1][22m[39m 17189591-1ed3-4d63-a828-ccae26e21022: Launching container wpilib/axon-dataset
[90m[2m[1][22m[39m .zip file extension found, interpreting as tensorflow object detection csv zip


[90m[2m[1][22m[39m treating as zip of tf obj detect


[90m[2m[1][22m[39m /home/Oxford Pets.v2-by-species.tensorflow/test/_annotations.csv


[90m[2m[1][22m[39m Traceback (most recent call last):


[90m[2m[1][22m[39m   File "tar_to_record.py", line 83, in <module>


[90m[2m[1][22m[39m     main(DATASET_PATHS, PERCENT_EVAL, DIRECTORY)


[90m[2m[1][22m[39m   File "tar_to_record.py", line 63, in main


[90m[2m[1][22m[39m     generate_tfrecord.main(EXTRACT_PATH + "/" + DATASET_NAME + "/test/_annotations.csv", join(OUTPUT_PATH, 'eval.record'), NORMAL_MODE, EXTRACT_PATH + "/" + DATASET_NAME + "/test/")


[90m[2m[1][22m[39m   File "/tensorflow/models/research/generate_tfrecord.py", line 84, in main


[90m[2m[1][22m[39m     examples = pd.read_csv(input_csv)


[90m[2m[1][22m[39m   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 678, in parser_f


[90m[2m[1][22m[39m     return _read(filepath_or_buffer, kwds)


[90m[2m[1][22m[39m   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 440, in _read


[90m[2m[1][22m[39m     parser = TextFileReader(filepath_or_buffer, **kwds)


[90m[2m[1][22m[39m   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 787, in __init__


[90m[2m[1][22m[39m     self._make_engine(self.engine)


[90m[2m[1][22m[39m   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine


[90m[2m[1][22m[39m     self._engine = CParserWrapper(self.f, **self.options)


[90m[2m[1][22m[39m   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1708, in __init__


[90m[2m[1][22m[39m     self._reader = parsers.TextReader(src, **kwds)


[90m[2m[1][22m[39m   File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__


[90m[2m[1][22m[39m   File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source


[90m[2m[1][22m[39m IOError: File /home/Oxford Pets.v2-by-species.tensorflow/test/_annotations.csv does not exist
```

**Comment by GrantPerkins** [comment]
To be clear, `/home/Oxford Pets.v2-by-species.tensorflow/test/_annotations.csv` does not exist. My dataset is not named `Oxford Pets.v2-by-species.tensorflow/` anymore, I renamed it.
