### ISSUE TITLE
Corrupt Image prevents viewing entire dataset

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/Axon#240]
```
[1] TypeError: Corrupt JPG, exceeded buffer limits
[1]     at validateBuffer (/usr/src/app/node_modules/image-size/dist/types/jpg.js:77:15)
[1]     at Object.calculate (/usr/src/app/node_modules/image-size/dist/types/jpg.js:101:13)
[1]     at lookup (/usr/src/app/node_modules/image-size/dist/index.js:35:49)
[1]     at Function.imageSize (/usr/src/app/node_modules/image-size/dist/index.js:109:16)
[1]     at /usr/src/app/packages/server/src/datasources/dataset-service.ts:169:38
[1]     at Array.map (<anonymous>)
[1]     at DatasetService.listImages (/usr/src/app/packages/server/src/datasources/dataset-service.ts:167:20)
[1]     at DatasetService.getDatasetImages (/usr/src/app/packages/server/src/datasources/dataset-service.ts:80:16)
```
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/3799260/123817052-accca780-d8ac-11eb-88a7-94371d830922.png">

**Comment by GrantPerkins** [comment]
Probably should remove that image from the dataset. Or even better, check validity of images during the dataset creation process. Or both.

**Comment by GrantPerkins** [comment]
The Python Imaging Library believes these "corrupt" images are valid. Ran `im.verify()`, no issues found.
